### ISSUE TITLE
Explanation of regular expression

### ISSUE THREAD

**Issue by severinsimmler** [The-Orizon/nlputils#3]
Can you explain what this regular expression:

https://github.com/The-Orizon/nlputils/blob/219927289f6fc142212490de73623d76849b38c6/detokenizer.py#L5

is supposed to match?

**Comment by gumblex** [comment]
Match whitespaces between CJK characters or full-width punctuation. This script removes unneeded spaces between Chinese/Japanese words.

**Comment by severinsimmler** [comment]
Thank you for the quick response.
